FROM debian:9
 
# Update and install all necessary packages (vim for debugging)
RUN apt-get update && apt-get install -y \
    apache2 \
    php \
    php-mysql \
    mariadb-server \
    mariadb-client \
    python \
    python-mysqldb \
    gdb \
    vim \
    && apt-get clean

# Open ports
EXPOSE 80
EXPOSE 3306

# apache configuration
RUN printf "RemoveHandler .html .htm \nAddType application/x-httpd-php .php .htm .html" >> /etc/apache2/apache2.conf
COPY initializeDB.sql initializeDB.sql

# Start services as last step
COPY startServices.sh startServices.sh
RUN chmod u+x startServices.sh
# CMD will run evertime the container starts up
CMD ./startServices.sh


