FROM resin/rpi-raspbian
 
# Update and install all necessary packages
RUN apt-get update && apt-get install -y \
    apache2 \
    php5 \
    php5-mysql \
    mariadb-server \
    mariadb-client \
    python \
    python-mysqldb \
    && apt-get clean

# Open ports
EXPOSE 80

# Copy sql script into the container to initialize the DB
COPY initializeDB.sql . 

# Start services as last step
COPY startServices.sh startServices.sh
RUN chmod u+x startServices.sh
# CMD will run evertime the container starts up
CMD ./startServices.sh


