FROM resin/rpi-raspbian
 
# Update and install all necessary packages
RUN apt-get update && apt-get install -y \
    apache2 \
    php5 \ 
    && apt-get clean

# Open ports
EXPOSE 80

# Start apache
CMD apachectl -D FOREGROUND

